apiVersion: apps/v1 
kind: Deployment
metadata:
  name: repo-1-hello
  labels: 
     app: repo-1-hello

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: repo-1-hello

  template:
    metadata:
      labels:
        app: repo-1-hello
    spec:
      containers:
      - name: repo-1-hello
        image: vmns/repo-1-hello
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
